config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :pictures do
    member do
      get 'modal'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show, :edit, :update]
  resources :articles
  resources :site_content, only: [:edit, :update]
  resources :members
  resources :labels, except: [:show]
  resources :designs

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/orders', to: 'orders#index', as: :orders
  get '/orders/new', to: 'orders#new', as: :new_order
  post '/orders', to: 'orders#create', as: :create_order

  get '/designs/:design_id/labels', to: 'designs#edit_labels', as: :design_edit_labels
  post '/designs/:design_id/addlabel/:label_id', to: 'designs#add_label', as: :design_add_label
  post '/designs/:design_id/removelabel/:label_id', to: 'designs#remove_label', as: :design_remove_label

  # Defines the root path route ("/")
  root 'site#home'
  get '/faq', to: 'site#faq'
  get '/join-us', to: 'site#join', as: :join


  #get 'enquiry/set', as: :set_enquiry
  #get 'enquiry/unset', as: :unset_enquiry
  #get 'enquiry/export', as: :export_enquiry
  # redirect to route on not found error
  # temporary solution for staging

end

app/models/design.rb
# == Schema Information
#
# Table name: designs
#
#  id          :bigint           not null, primary key
#  created     :datetime
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Design < ApplicationRecord
  has_one_attached :image
  has_many :design_labels, dependent: :destroy
  has_many :labels, through: :design_labels

  validates :name, presence: true, length: { maximum: 30 }
  validates :description, length: { maximum: 200 }
  validates :created, presence: true
  validates :image, presence: true, aspect_ratio: :square, processable_image: true
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :set_design, only: %i[show edit update destroy]

  # GET /designs or /designs.json
  def index
    @designs = Design.order(created: :desc)
  end

  # GET /designs/1 or /designs/1.json
  def show; end

  # GET /designs/new
  def new
    @design = Design.new
    authorize @design
  end

  # GET /designs/1/edit
  def edit
    authorize @design
  end

  # POST /designs or /designs.json
  def create
    @design = Design.new(design_params)
    authorize @design

    respond_to do |format|
      if @design.save
        format.html { redirect_to designs_url, notice: 'Folt sikeresen létrehozva.' }
        format.json { render :show, status: :created, location: @design }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designs/1 or /designs/1.json
  def update
    authorize @design
    respond_to do |format|
      if @design.update(design_params)
        format.html { redirect_to designs_url, notice: 'Folt sikeresen frissítve.' }
        format.json { render :show, status: :ok, location: @design }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designs/1 or /designs/1.json
  def destroy
    authorize @design
    @design.destroy

    respond_to do |format|
      format.html { redirect_to designs_url, notice: 'Folt sikeresen törölve.' }
      format.json { head :no_content }
    end
  end

  def edit_labels
    @design = Design.find(params[:design_id])
    authorize @design
    @active_tags = @design.labels
    active_ids = @design.labels.pluck(:id)
    @inactive_tags = Label.where.not(id: active_ids)
  end

  def add_label
    design = Design.find(params[:design_id])
    authorize design
    label = Label.find(params[:label_id])
    design.labels << label
    if design.save
      redirect_to design_edit_labels_url(design), notice: 'Címke sikeresen hozzáadva.'
    else
      redirect_to design_edit_labels_url(design), alert: 'Címke hozzáadása sikertelen.'
    end
  end

  def remove_label
    design = Design.find(params[:design_id])
    authorize design
    label = design.labels.find(params[:label_id])
    design.labels.delete(label)
    if design.save
      redirect_to design_edit_labels_url(design), notice: 'Címke sikeresen törölve.'
    else
      redirect_to design_edit_labels_url(design), alert: 'Címke törlése sikertelen.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_design
    @design = Design.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def design_params
    params.require(:design).permit(:name, :description, :created, :image)
  end
end

app/views/designs/_design.html.erb
<div id="<%= dom_id design %>">

  <div class="relative rounded shadow-lg bg-white m-2 max-w-[200px] justify-self-center">
    <%= image_tag design.image, alt: design.name, class: 'rounded-t-lg max-w-[200px]' %>
    <% if policy(design).edit? %>
      <div class="absolute -top-1 -right-1 flex justify-start">
        <%= link_to design_edit_labels_url(design), class: 'shadow-lg' do %>
          <i class="fa-solid fa-tags icon-edit mr-2 shadow-lg"></i>
        <% end %>

        <%= link_to edit_design_path(design), class: 'shadow-lg' do %>
          <i class="fa-solid fa-pen-to-square icon-edit mr-2 shadow-lg"></i>
        <% end %>

        <%= button_to design_path(design), class: 'shadow-lg', method: :delete, form: { data: { 'turbo_confirm': 'Biztos vagy benne? A törlés véglges!' } } do %>
          <i class="fa-solid fa-trash icon-delete shadow-lg"></i>
        <% end %>
      </div>
    <% end %>
    <div class="px-2 py-2 ">
      <div class="flex flex-row flex-wrap m-0 p-0" style="flex-wrap: wrap;">
        <% design.labels.each do |label| %>
          <div class="bg-gray-700 rounded-md text-white text-sm p-1 m-1">
            <%= label.name.upcase %>
          </div>
        <% end %>
      </div>
      
      <span class=" font-bold text-xl mb-2 text-primary"> <%= link_to design.name, design_path(design)%> </span>

      <%= design.created.strftime("%Y.%m.%d.") %>

      <div class="text-gray-800 italic break-words">
        <%= design.description.truncate_words(9) %>
        <% if design.description.length > 9 %>
          <%= link_to 'tovább', design_path(design), class: 'text-red underline' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/designs/_form.html.erb
<%= form_with(model: design, class: "contents") do |form| %>
  <% if design.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= design.errors.count %> probléma miatt nem lehetséges a mentés:</h2>

      <ul>
        <% design.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :created %>
    <%= form.date_field :created, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, maxlength:200, size:'3*75', class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <% if design.image.attached? %>
    <label> Jelenlegi kép</label>
    <div class="my-5">
      <%= image_tag design.image %>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/designs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Folt szerkesztése</h1>

  <%= render "form", design: @design %>

  <div class="flex flex-row flex-wrap mt-4" style="flex-wrap: wrap;" >
    <%= link_to "Vissza a foltokhoz", designs_path, class: "btn btn-secondary" %>
    <%= button_to "Folt törlése", design_path(@design), method: :delete, form: { data: { 'turbo_confirm': 'Biztos vagy benne? A törlés végleges!' } }, class: "btn btn-danger ml-3" %>
  </div>
</div>

app/views/designs/edit_labels.html.erb
<div class="w-full">
  <div class="mb-5">
    <%= link_to 'Vissza a foltokhoz', designs_path, class: 'btn btn-secondary', data: { turbo: false } %>
  </div>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl mb-5"><%= @design.name %></h1>
  </div>

  <p>Kattints a címkére az aktiváláshoz vagy a deaktiváláshoz!</p>
  <h3 class="font-bold text-xl">Aktív címkék:</h1>
  <div class="flex flex-row flex-wrap" style="flex-wrap: wrap;">
    <% @active_tags.each do |tag| %>
      <div class="bg-gray-700 rounded-md text-white text-sm p-1 m-2">
        <%= button_to tag.name.upcase, design_remove_label_url(@design, tag), method: :post %>
      </div>
    <% end %>
  </div>

  <h3 class="font-bold text-xl">Inaktív címkék:</h1>
  <div class="flex flex-row flex-wrap" style="flex-wrap: wrap;">
    <% @inactive_tags.each do |tag| %>
      <div class="bg-gray-700 rounded-md text-white text-sm p-1 m-2">
        <%= button_to tag.name.upcase, design_add_label_url(@design, tag), method: :post %>
      </div>
    <% end %>
  </div>
</div>

app/views/designs/index.html.erb
<div class="w-full">

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl mb-5">Legacy foltok</h1>
    <span>
      <% if policy(Design).new? %>
        <%= link_to 'Új folt', new_design_path, class: "btn btn-secondary m-4" %>
        <%= link_to 'Címkék', labels_path, class: "btn btn-secondary m-4" %>
      <% end %>
    </span>
  </div>

  <div class="lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-2 mobile:grid-cols-1 xl:grid-cols-5 justify-around" style="display:grid;">
    <% @designs.each do |design| %>
      <div class="m-4 justify-self-center">
        <%= render design %>
      </div>
    <% end %>
  </div>
</div>

app/views/designs/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Új folt</h1>

  <%= render "form", design: @design %>

  <%= link_to 'Vissza a foltokhoz', designs_path, class: "btn btn-secondary ml-3" %>
</div>

app/views/designs/show.html.erb
<div>
  <%= link_to 'Vissza a foltokhoz', designs_path, class: 'btn btn-secondary m-4', data: { turbo: false } %>
</div>
<br>
<div class="flex flex-row flex-nowrap gap-4 place-content-center">
  <%= image_tag @design.image , alt: @design.name , class: 'rounded-lg max-w-[200px] justify-self-end' %>
  <div>

    <div>
      <span class=" font-bold text-xl mb-2 text-primary"> <%= @design.name %> </span>
      <br>
      <%= @design.created.strftime("%Y.%m.%d.") %>
      <br>
      <div class="flex flex-row flex-wrap m-0 p-0" style="flex-wrap: wrap;">
        <% @design.labels.each do |label| %>
          <div class="bg-gray-700 rounded-md text-white text-sm p-1 m-1">
            <%= label.name.upcase %>
          </div>
        <% end %>
      </div>
      <br>
      <div class="text-gray-800 italic break-words">
        <%= @design.description %>
      </div>
    </div>

  </div>
  <br>
</div>