config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :pictures do
    member do
      get 'modal'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show, :edit, :update]
  resources :articles
  resources :site_content, only: [:edit, :update]
  resources :members
  resources :labels, except: [:show]
  resources :designs

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/orders', to: 'orders#index', as: :orders
  get '/orders/new', to: 'orders#new', as: :new_order
  post '/orders', to: 'orders#create', as: :create_order

  get '/designs/:design_id/labels', to: 'designs#edit_labels', as: :design_edit_labels
  post '/designs/:design_id/addlabel/:label_id', to: 'designs#add_label', as: :design_add_label
  post '/designs/:design_id/removelabel/:label_id', to: 'designs#remove_label', as: :design_remove_label

  # Defines the root path route ("/")
  root 'site#home'
  get '/faq', to: 'site#faq'
  get '/join-us', to: 'site#join', as: :join


  #get 'enquiry/set', as: :set_enquiry
  #get 'enquiry/unset', as: :unset_enquiry
  #get 'enquiry/export', as: :export_enquiry
  # redirect to route on not found error
  # temporary solution for staging

end

app/models/label.rb
# == Schema Information
#
# Table name: labels
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Label < ApplicationRecord
  has_many :design_labels, dependent: :destroy
  has_many :designs, through: :design_labels

  validates :name, presence: true, length: { maximum: 15 }
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[ show edit update destroy ]

  # GET /labels or /labels.json
  def index
    authorize Label.new
    @labels = Label.all
  end

  # GET /labels/new
  def new
    @label = Label.new
    authorize @label
  end

  # GET /labels/1/edit
  def edit
    authorize @label
  end

  # POST /labels or /labels.json
  def create
    @label = Label.new(label_params)
    authorize @label

    respond_to do |format|
      if @label.save
        format.html { redirect_to labels_url, notice: "Címke sikeresen létrehozva." }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    authorize @label

    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to labels_url, notice: "Címke sikeresen módosítva." }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    authorize @label
    @label.destroy

    respond_to do |format|
      format.html { redirect_to labels_url, notice: "Címke sikeresen törölve." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def label_params
      params.require(:label).permit(:name)
    end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: label, class: "contents") do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= label.errors.count %> probléma miatt nem lehetséges a mentés:</h2>

      <ul>
        <% label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label 'Címke neve' %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/labels/_label.html.erb
<div id="<%= dom_id label %>">
  <div class="bg-gray-700 rounded-md text-white text-sm p-1 m-2">
    <%= link_to label.name.upcase, edit_label_path(label) %>
  </div>
</div>

app/views/labels/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Címke szerkesztése</h1>

  <%= render "form", label: @label %>

  <div class="flex flex-row flex-wrap mt-4" style="flex-wrap: wrap;" >
    <%= link_to "Vissza a címkékhez", labels_path, class: "btn btn-secondary" %>
    <%= button_to "Címke törlése", label_path(@label), method: :delete, form: { data: { 'turbo_confirm': 'Biztos vagy benne? A törlés végleges!' } }, class: "btn btn-danger ml-3" %>
  </div>
</div>

app/views/labels/index.html.erb
<div class="w-full">

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl mb-5">Címkék</h1>
    <span>
      <%= link_to 'Címke hozzáadása', new_label_path, class: "btn btn-secondary m-4" %>
      <%= link_to 'Legacy foltok', designs_path, class: "btn btn-secondary m-4" %>
    </span>  
  </div>

  <div class="flex flex-row flex-wrap" style="flex-wrap: wrap;" >
    <% @labels.each do |label| %>
      <div class="m-1 justify-self-center">
        <%= render label %>
      </div>
    <% end %>
  </div>
</div>

app/views/labels/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Új címke hozzáadása</h1>

  <%= render "form", label: @label %>

  <%= link_to 'Vissza a címkékhez', labels_path, class: "btn btn-secondary ml-3" %>
</div>