config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :pictures do
    member do
      get 'modal'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show, :edit, :update]
  resources :articles
  resources :site_content, only: [:edit, :update]
  resources :members
  resources :labels, except: [:show]
  resources :designs

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/orders', to: 'orders#index', as: :orders
  get '/orders/new', to: 'orders#new', as: :new_order
  post '/orders', to: 'orders#create', as: :create_order

  get '/designs/:design_id/labels', to: 'designs#edit_labels', as: :design_edit_labels
  post '/designs/:design_id/addlabel/:label_id', to: 'designs#add_label', as: :design_add_label
  post '/designs/:design_id/removelabel/:label_id', to: 'designs#remove_label', as: :design_remove_label

  # Defines the root path route ("/")
  root 'site#home'
  get '/faq', to: 'site#faq'
  get '/join-us', to: 'site#join', as: :join


  #get 'enquiry/set', as: :set_enquiry
  #get 'enquiry/unset', as: :unset_enquiry
  #get 'enquiry/export', as: :export_enquiry
  # redirect to route on not found error
  # temporary solution for staging

end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id          :bigint           not null, primary key
#  author      :string
#  description :string
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Picture < ApplicationRecord
  has_one_attached :img

  validates :name, presence: true, length: { maximum: 50 }
  validates :author, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 200 }
  validates :img, presence: true
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[show modal edit update destroy]
  # GET /pictures or /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1 or /pictures/1.json
  def show; end

  def modal; end

  # GET /pictures/new
  def new
    @picture = Picture.new
    authorize @picture
  end

  # GET /pictures/1/edit
  def edit
    authorize @picture
  end

  # POST /pictures or /pictures.json
  def create
    @picture = Picture.new(picture_params)
    authorize @picture

    respond_to do |format|
      if @picture.save
        format.html { redirect_to picture_url(@picture), notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1 or /pictures/1.json
  def update
    authorize @picture
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to picture_url(@picture), notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1 or /pictures/1.json
  def destroy
    authorize @picture
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_picture
    @picture = Picture.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def picture_params
    params.require(:picture).permit(:name, :author, :description, :img)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_with(model: picture, class: "contents") do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :author %>
    <%= form.text_field :author, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, maxlength:200, size:'3*75', class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :img %>
    <%= form.file_field :img, class: "block shadow rounded border border-gray-200 outline-none px-3 py-2 mt-2 w-full", accept: 'image/png,image/gif,image/jpeg' %>
  </div>

  <% if picture.img.attached? %>
    <label> Jelenlegi képfájl</label>
    <div class="my-5">
      <%= image_tag picture.img %>
    </div>

  <% end %>

  <div class="inline">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pictures/_picture.html.erb
<div id="<%= dom_id picture %>">

  <div class="relative max-w-sm rounded shadow-lg bg-white m-2 hover:shadow-xl">
    <%= link_to modal_picture_path(picture), data:{turbo_frame: "modal-image"} do %>
      <%= image_tag picture.img, alt: picture.name, class: 'brightness-90 hover:brightness-100 rounded-t-lg' %>
    <% end %>
    <% if policy(picture).edit? %>
      <div class="absolute -top-1 -right-1 flex justify-start">
        <%= link_to edit_picture_path(picture), class: 'shadow-lg' do %>
          <i class="fa-solid fa-pen-to-square icon-edit mr-2 shadow-lg"></i>
        <% end %>

        <%= button_to picture_path(picture), class: 'shadow-lg', method: :delete, form: { data: { 'turbo_confirm': 'Biztos vagy benne? A törlés véglges!' } } do %>
          <i class="fa-solid fa-trash icon-delete shadow-lg"></i>
        <% end %>
      </div>
    <% end %>
    <div class="px-6 py-4 ">
      <span class=" font-bold text-xl mb-2 text-primary"> <%= picture.name%> </span>

      <span class="text-gray-500 font-bold">
        by <%= picture.author %>
      </span>

      <div class="text-gray-800 italic break-words">
        <%= picture.description %>
      </div>
    </div>
  </div>
</div>

app/views/pictures/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Kép módosítása</h1>

  <%= render "form", picture: @picture %>

  <%= link_to 'Vissza a gallériához', pictures_path, class: "btn btn-secondary ml-3" %>
</div>

app/views/pictures/index.html.erb
<div class="w-full">

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl mb-5">Galéria</h1>
    <% if policy(Picture).new? %>
      <%= link_to 'Kép hozzáadása', new_picture_path, class: "btn btn-secondary" %>
    <% end %>
  </div>


  <div data-controller="gallery" data-action="turbo:load@window->gallery#layout">
    <% @pictures.each do |picture| %>
      <div class="grid-item">
        <%= render 'picture', picture: picture %>
      </div>
    <% end %>
  </div>

  <%= turbo_frame_tag "modal-image" %>
</div>

app/views/pictures/modal.html.erb
<%= turbo_frame_tag "modal-image" do %>
  <div class="fixed top-0 left-0 z-80 w-screen h-screen bg-black/70 flex justify-center items-center">
    <span class="fixed z-90 top-6 right-8 text-white text-5xl font-bold">
       <%= link_to pictures_path do %>
          <span>&times;</span>
        <% end %>
    </span>
    <%= image_tag @picture.img, alt: @picture.name, class: "max-w-[800px] max-h-[600px] object-cover" %>
  </div>
<% end %>

app/views/pictures/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Kép hozzáadása gallériához</h1>

  <%= render "form", picture: @picture %>

  <%= link_to 'Vissza a gallériához', pictures_path, class: "btn btn-secondary ml-3" %>
</div>

app/views/pictures/show.html.erb
<div class="grid grid-cols-1 gap-10 w-full md:grid-cols-2 ">
  <div>

    <%= image_tag @picture.img, alt: @picture.name %>
  </div>
  <!-- ... -->
  <div>

    <div>
      <span class="font-bold">Cím: </span>
      <%= @picture.name %>
      <hr/>
      <span class="font-bold">Készítő: </span>
      <%= @picture.author %>
      <hr/>
      <span class="font-bold">Leírás: </span>
      <%= @picture.description %>
    </div>

  </div>
  <div>
    <%= link_to 'Vissza a galériához', pictures_path, class: 'btn btn-secondary ', data: { turbo: false } %>
  </div>
</div>