config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :pictures do
    member do
      get 'modal'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show, :edit, :update]
  resources :articles
  resources :site_content, only: [:edit, :update]
  resources :members
  resources :labels, except: [:show]
  resources :designs

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/orders', to: 'orders#index', as: :orders
  get '/orders/new', to: 'orders#new', as: :new_order
  post '/orders', to: 'orders#create', as: :create_order

  get '/designs/:design_id/labels', to: 'designs#edit_labels', as: :design_edit_labels
  post '/designs/:design_id/addlabel/:label_id', to: 'designs#add_label', as: :design_add_label
  post '/designs/:design_id/removelabel/:label_id', to: 'designs#remove_label', as: :design_remove_label

  # Defines the root path route ("/")
  root 'site#home'
  get '/faq', to: 'site#faq'
  get '/join-us', to: 'site#join', as: :join


  #get 'enquiry/set', as: :set_enquiry
  #get 'enquiry/unset', as: :unset_enquiry
  #get 'enquiry/export', as: :export_enquiry
  # redirect to route on not found error
  # temporary solution for staging

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    @articles = Article.last(3)
    @services = [1, 2, 3, 4].map do |i|
      SiteContent.find_or_create_by(name: "MainService#{i}")
    end
  end

  def faq
    @content = SiteContent.find_or_create_by(name: "faq"){|c| c.title = "Gyakran ismételt kérdések"}
  end

  def join
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/faq.html.erb
<% frame_id = dom_id(@content, "edit_turbo_frame") %>
<%= turbo_frame_tag frame_id do %>

  <h1 class="font-medium leading-tight text-5xl mt-0 mb-2 text-black">
    <%= @content.title %>
    <% if policy(@content).edit? %>
      <%= link_to edit_site_content_path(@content, back_path:faq_path) do %>
        <i class="fa-solid fa-pen-to-square hover:text-yellow-400"></i>
      <% end %>
    <% end %>
  </h1>
  <%= @content.content %>

<% end %>

app/views/site/home.html.erb
<div class="w-full">
  <div class="flex" style="height:600px;">
    <div class="flex items-center text-center lg:text-left px-8 md:px-12 lg:w-1/2">
      <div>
        <h2 class="text-3xl font-semibold text-gray-800 md:text-4xl">
          Valósítsd meg <span class="text-primary">ötleteid</span> velünk!
        </h2>
        <p class="mt-2 text-sm text-gray-500 md:text-base">
          A <span class="text-primary">Pulcsi és FoltMékör</span> – közismertebb nevén a Hímzőkör – a Ház egyik kreatív csoportjaként működik. Már több mint 15 éve azon munkálkodunk, hogy minden VIK-es egyedi módon gyűjthesse emlékeit a villanykari pulcsival és a rá való foltokkal. Egész évben foltok és pólók hímzésével foglalkozunk egy ipari hímzőgép segítségével, aminek programozása és működtetése felér egy kisebb tudománnyal! Szeretnél saját foltot vagy mintát a pulcsidra? Bátran keress fel minket!
        </p>
        <div class="flex justify-center lg:justify-start mt-6">
          <a class="px-4 btn btn-primary" href="#services">
            Szolgáltatásaink
          </a>
          <%= link_to 'Képek a munkáinkról', pictures_path, class: 'ml-4 btn btn-secondary', data: { turbo: false } %>
        </div>
      </div>
    </div>
    <div class="hidden lg:block lg:w-1/2" style="clip-path:polygon(10% 0, 100% 0%, 100% 100%, 0 100%)">
      <div class="h-full object-cover"
           style="background-image: url(<%= image_url("hero4.jpg") %>); background-position: center; background-size: cover;">
        <div class="h-full bg-black opacity-25"></div>
      </div>
    </div>
  </div>
</div>

<% if @articles&.any? %>
  <div class="px-4 py-16">
    <h1 class="mb-8 text-center text-3xl font-bold">Legutóbbi híreink</h1>

    <ol class="justify-start sm:flex">
      <% @articles.each do |article| %>
        <li class="relative flex-1 mb-6 sm:mb-0">
          <div class="flex items-center">
            <div class="flex z-10 justify-center items-center w-18 h-18 bg-gray-100 rounded-full ring-0 ring-white shrink-0 ">
              <svg aria-hidden="true" class="w-6 h-6 text-red-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd"></path>
              </svg>
            </div>
            <div class="hidden sm:flex w-full bg-gray-200 h-0.5"></div>
          </div>
          <div class="mt-3 sm:pr-8">
            <%= link_to article.title, article_path(article), class: 'text-lg font-semibold text-primary' %>

            <time class="block mb-2 text-sm font-normal leading-none text-gray-400"><%= article.updated_at.in_time_zone('Budapest').strftime('%Y. %B %e. %H:%M') %></time>
            <p class="text-base font-normal text-gray-500"><%= article.intro.truncate(128, separator: ' ') %></p>
          </div>
        </li>

      <% end %>
    </ol>

    <div class="mt-10 flex items-center justify-center gap-4">
      <%= link_to 'További híreink', articles_path, class: 'btn btn-primary', data: { turbo: false } %>
    </div>
  </div>
<% end %>


<div id="default-carousel" class="relative my-16" data-carousel="slide">
  <!-- Carousel wrapper -->
  <div class="relative h-56 overflow-hidden rounded-lg md:h-96">
    <!-- Item 1 -->
    <div class="duration-700 ease-in-out absolute inset-0 transition-all transform translate-x-0 z-20" data-carousel-item="">
      <img src="<%= image_url("hero.jpg") %>" class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
    </div>
    <!-- Item 2 -->
    <div class="duration-700 ease-in-out absolute inset-0 transition-all transform translate-x-full z-10" data-carousel-item="">
      <img src="<%= image_url("hero2.jpg") %>" class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
    </div>
    <!-- Item 3 -->
    <div class="duration-700 ease-in-out absolute inset-0 transition-all transform -translate-x-full z-10" data-carousel-item="">
      <img src="<%= image_url("hero3.jpg") %>" class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
    </div>
  </div>
  <!-- Slider indicators -->
  <div class="absolute z-30 flex space-x-3 -translate-x-1/2 bottom-5 left-1/2">
    <button type="button" class="w-3 h-3 rounded-full bg-white" aria-current="true" aria-label="Slide 1" data-carousel-slide-to="0"></button>
    <button type="button" class="w-3 h-3 rounded-full bg-white/50" aria-current="false" aria-label="Slide 2" data-carousel-slide-to="1"></button>
    <button type="button" class="w-3 h-3 rounded-full bg-white/50" aria-current="false" aria-label="Slide 3" data-carousel-slide-to="2"></button>
  </div>
  <!-- Slider controls -->
  <button type="button" class="absolute top-0 left-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-prev="">
        <span class="inline-flex items-center justify-center w-8 h-8 rounded-full sm:w-10 sm:h-10 bg-white/30 group-hover:bg-white/50 group-focus:ring-4 group-focus:ring-white group-focus:outline-none">
            <svg aria-hidden="true" class="w-5 h-5 text-white sm:w-6 sm:h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></svg>
            <span class="sr-only">Previous</span>
        </span>
  </button>
  <button type="button" class="absolute top-0 right-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-next="">
        <span class="inline-flex items-center justify-center w-8 h-8 rounded-full sm:w-10 sm:h-10 bg-white/30 group-hover:bg-white/50 group-focus:ring-4 group-focus:ring-white group-focus:outline-none">
            <svg aria-hidden="true" class="w-5 h-5 text-white sm:w-6 sm:h-6 " fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg>
            <span class="sr-only">Next</span>
        </span>
  </button>
</div>

<div class="px-4 py-16" id="services">
  <h1 class="mb-8 text-center text-3xl font-bold">Szolgáltatásaink</h1>

  <ul class="grid place-content-center sm:grid-cols-2 gap-8 mx-auto">
    <% @services.each_with_index  do |service, i| %>
      <li class="flex justify-center">
        <div class="pl-6 pr-4 text-5xl font-extralight text-primary">0<%= (i+1).to_s%>.</div>
        <div>
          <% frame_id = dom_id(service, "edit_turbo_frame") %>
          <%= turbo_frame_tag frame_id do %>
            <div class="text-xl font-bold text-primary block" style="width: 10rem">
              <%= service.title %>
              <% if policy(service).edit? %>
                <%= link_to edit_site_content_path(service) do %>
                  <i class="fa-solid fa-pen-to-square text-black hover:text-yellow-400"></i>
                <% end %>
              <% end %>
            </div>
            <p class="max-w-xs py-2 text-sm">
              <%= service.content.to_plain_text %>
            </p>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<div class="py-24 flex items-center justify-center">
  <div class="mx-auto">
    <div class="text-center">
      <h1 class="mt-3 text-3xl sm:text-[3.5rem] font-bold leading-[4rem] tracking-tight text-black">Keress minket bátran
        elérhetőségeinken!</h1>
      <p class="mt-3 text-lg leading-relaxed text-slate-400">
        E-mail címünk: <a class="link" href="mailto:himzo@sch.bme.hu">himzo@sch.bme.hu</a>,<br/>
        körünk jelenlegi körvezetőjét a
        <a class="link" href="https://pek.sch.bme.hu/groups/339" target="_blank">PéK-en találod meg</a>!
      </p>
    </div>

    <div class="mt-6 flex items-center justify-center gap-4">
      <%= link_to 'Rendelnék!', orders_path, class: 'btn btn-primary'%>
      <%= link_to 'További tudnivalók', faq_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/site/join.html.erb
<% if ENV["HIMZOSCH_JOIN_URL"].present? %>
  <iframe src="<%= ENV["HIMZOSCH_JOIN_URL"] %>" class="w-2/3 mobile:w-11/12" height="1000" frameborder="0" style="margin-left: auto;margin-right: auto;">Betöltés…</iframe>
<% else %>
  <p class="text-center text-3xl">Jelenleg nincs lehetőség a jelentkezésre</p>
<% end %>